twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'Form/bootstrap_4_horizontal_layout.html.twig'
    globals:
        notications: "@App\\Service\\DBNotificationServiceInterface"

knp_paginator:
    template:
        pagination: bundles/knp/pagination.html.twig
eschmar_time_ago:
    format: 'Y-m-d H:i:s'
