vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix:         '%app.path.user_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_images%'
