version: '3.4'

services:
  db-yktr-dev:
    image: postgres:10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 53306:5432
    networks:
      - traefik
  php-yktr-dev:
    build: ./docker/php
    links:
    - db
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - .:/var/www/yktr
    networks:
    - traefik

  web-yktr-dev:
    image: nginx:1.15
    depends_on:
    - php
    - db
    volumes:
    - .:/var/www/yktr
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
    - traefik
    labels:
    - "traefik.backend=yktr-dev"
    - "traefik.frontend.rule=Host:dev.yktr.io"
    - "trafik.enable=true"
    - "traefik.port=80"
    - "traefik.protocol=http"
    - "traefik.frontend.entryPoints=http"
networks:
  traefik:
    external: true
