version: '3.4'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
    - ./docker/.data/db:/var/lib/mysql
    ports:
    - 53306:5432

  php:
    build: ./docker/php
    ports:
    - 59000:9000
    links:
    - db
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - .:/var/www/yktr

  web:
    image: nginx:1.15
    ports:
    - "8000:80"
    depends_on:
    - php
    - db
    volumes:
    - .:/var/www/yktr
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
