version: '3.4'

services:
  db-yktr-dev:
    image: postgres:10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 53306:5432
  php-yktr-dev:
    build: ./docker/php
    links:
    - db-yktr-dev
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - .:/var/www/yktr
    environment:
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
      PHP_BLACKFIRE: 1

  web-yktr-dev:
    image: nginx:1.15
    depends_on:
    - php-yktr-dev
    - db-yktr-dev
    volumes:
    - .:/var/www/yktr
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8080:80
    labels:
    - "traefik.backend=yktr-dev"
    - "traefik.frontend.rule=Host:dev.yktr.io"
    - "trafik.enable=true"
    - "traefik.port=80"
    - "traefik.protocol=http"
    - "traefik.frontend.entryPoints=http"

  blackfire:
    image: blackfire/blackfire
    container_name: "yktr_blackfire"
    environment:
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
