version: '3.4'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
    - ./docker/.data/db:/var/lib/mysql
    ports:
    - 53306:3306

  php:
    build: ./docker/php
    ports:
    - 59000:9000
    links:
    - db
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - .:/var/www/yktr

  web:
    image: nginx:1.15
    ports:
    - "8000:80"
    depends_on:
    - php
    volumes:
    - .:/var/www/yktr
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
