controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    prefix: /

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: /admin

controllers:
    resource: ../../src/Controller
    type: annotation